name: eval

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Upate dist
      run: |
        sh ./util/evaluate.sh
    - name: Commit files
      run: |
        git config --local user.email "koyamaso0309@gmail.com"
        git config --local user.name "KoyamaSohei"
        git commit -m "Update dist" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}